
version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
  api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - api-network
  
  image-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=image_extractor
    environment:
      - EXTRACTOR_TYPE=image_extractor
    env_file:
      - .env
  script-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=script_extractor
    environment:
      - EXTRACTOR_TYPE=script_extractor
    env_file:
      - .env
networks:
  api-network:
    driver: bridge
 