
version: '3.8'
services:
  ui:
    build:
      context: ./src/ui/
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    env_file:
      - .env
  api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
  image-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=image_extractor
    environment:
      - EXTRACTOR_TYPE=image_extractor
    env_file:
      - .env
  script-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=script_extractor
    environment:
      - EXTRACTOR_TYPE=script_extractor
    env_file:
      - .env