services:
  api:
    build:
      context: ./src/backend
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    env_file:
      - .env.local
  # image-extractor:
  #   build:
  #     context: ./src/backend
  #     dockerfile: ./image-extractor/Dockerfile
  #   env_file:
  #     - .env.local
  # script-extractor:
  #   build:
  #     context: ./src/backend
  #     dockerfile: ./script-extractor/Dockerfile
  #   env_file:
  #     - .env.local
  video-generator:
    build:
      context: ./src/backend
      dockerfile: ./video-generator/Dockerfile
    env_file:
      - .env.local
  video-transformation:
    build:
      context: ./src/backend
      dockerfile: ./video-transformation/Dockerfile
    env_file:
      - .env.local
  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - api
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8080/api
