
version: '3.8'
services:
  api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    env_file:
      - .env
  image-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=image_extractor
    environment:
      - EXTRACTOR_TYPE=image_extractor
    env_file:
      - .env
  script-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=script_extractor
    environment:
      - EXTRACTOR_TYPE=script_extractor
    env_file:
      - .env
  video-generator:
    build:
      context: ./src/video-generator/
      dockerfile: Dockerfile
    env_file:
      - .env
  video-concatenator:
    build:
      context: ./src/video-concatenator/
      dockerfile: Dockerfile
    env_file:
      - .env