version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # Modify this to 0.0.0.0 to make the app accessible outside the container
      - HOST=0.0.0.0
    command: python app.py
    restart: unless-stopped