
version: '3.8'
services:
  frontend:
    build:
      context: ./src/frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
  api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    env_file:
      - .env
  image-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=image_extractor
    environment:
      - EXTRACTOR_TYPE=image_extractor
    env_file:
      - .env
  script-extractor:
    build:
      context: ./src/extractors/
      dockerfile: Dockerfile
      args:
        - EXTRACTOR_TYPE=script_extractor
    environment:
      - EXTRACTOR_TYPE=script_extractor
    env_file:
      - .env
  # ui:
  #   build:
  #     context: ./src/ui/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - api
  #   environment:
  #     - API_URL=http://localhost:8080/api
