version: '3.8'
services:
  ppt-api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - ppt-api
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api